/**
 * Object storage for attachments. Two drivers behind one interface:
 *  - local disk (default; development, tests):   STORAGE_DIR (default ./.local/uploads)
 *  - S3-compatible (AWS S3, MinIO, R2, …):       S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_REGION
 * Callers never expose storage keys or URLs to users: downloads go through /api/v1/attachments/[id], which
 * looks the attachment up with the brand-scoped client first.
 */
import "server-only";
import { AwsClient } from "aws4fetch";
import fs from "node:fs/promises";
import path from "node:path";

export interface StorageDriver {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by us (no user input in path segments), but never allow traversal. */
function safeKey(key: string): string {
  if (!/^[A-Za-z0-9/_.-]+$/.test(key) || key.includes("..") || key.startsWith("/")) throw new Error("Invalid storage key");
  return key;
}

export function localDriver(root = process.env.STORAGE_DIR ?? path.join(process.cwd(), ".local", "uploads")): StorageDriver {
  const file = (key: string) => path.join(root, ...safeKey(key).split("/"));
  return {
    async put(key, bytes) {
      await fs.mkdir(path.dirname(file(key)), { recursive: true });
      await fs.writeFile(file(key), bytes);
    },
    async get(key) {
      return new Uint8Array(await fs.readFile(file(key)));
    },
    async delete(key) {
      await fs.rm(file(key), { force: true });
    },
  };
}

export function s3Driver(cfg: { endpoint: string; bucket: string; accessKeyId: string; secretAccessKey: string; region: string }): StorageDriver {
  const client = new AwsClient({ accessKeyId: cfg.accessKeyId, secretAccessKey: cfg.secretAccessKey, region: cfg.region, service: "s3" });
  const url = (key: string) => `${cfg.endpoint.replace(/\/$/, "")}/${cfg.bucket}/${safeKey(key)}`;
  const check = async (res: Response, op: string) => {
    if (!res.ok) throw new Error(`Storage ${op} failed (${res.status})`);
    return res;
  };
  return {
    async put(key, bytes, contentType) {
      await check(await client.fetch(url(key), { method: "PUT", body: bytes as BodyInit, headers: { "Content-Type": contentType } }), "upload");
    },
    async get(key) {
      const res = await check(await client.fetch(url(key)), "download");
      return new Uint8Array(await res.arrayBuffer());
    },
    async delete(key) {
      await check(await client.fetch(url(key), { method: "DELETE" }), "delete");
    },
  };
}

let driver: StorageDriver | undefined;

export function storage(): StorageDriver {
  if (driver) return driver;
  const { S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_REGION } = process.env;
  driver =
    S3_ENDPOINT && S3_BUCKET && S3_ACCESS_KEY_ID && S3_SECRET_ACCESS_KEY
      ? s3Driver({ endpoint: S3_ENDPOINT, bucket: S3_BUCKET, accessKeyId: S3_ACCESS_KEY_ID, secretAccessKey: S3_SECRET_ACCESS_KEY, region: S3_REGION ?? "us-east-1" })
      : localDriver();
  return driver;
}

/** Tests can swap the driver. */
export function setStorageDriver(d: StorageDriver | undefined) {
  driver = d;
}
