/**
 * Writes docs/SETUP_CATALOGUE.md from the Setup catalogue (src/server/modules/setup/catalogue.ts):
 *   pnpm setup:catalogue
 * A unit test fails when the document is older than the catalogue, so the status column cannot drift.
 */
import fs from "node:fs";
import path from "node:path";
import { SETUP_CATALOGUE, SETUP_CATEGORY_DEFS, hrefOf, type SetupEntry } from "../src/server/modules/setup/catalogue";

const STATUS = { DONE: "Done", PARTIAL: "In progress", PLANNED: "Planned" } as const;
const TIER = { SA: "**SA**", ADMIN: "ADMIN", BRAND_ADMIN: "BA", ALL: "All" } as const;

function tiers(e: SetupEntry): string {
  return e.tiers.map((t) => (t === "BRAND_ADMIN" && !e.brandAdminReady ? "BA (planned)" : TIER[t])).join(", ");
}

const cell = (s: string) => s.replace(/\|/g, "\\|");

export function renderCatalogue(): string {
  const done = SETUP_CATALOGUE.filter((e) => e.status === "DONE").length;
  const partial = SETUP_CATALOGUE.filter((e) => e.status === "PARTIAL").length;
  const planned = SETUP_CATALOGUE.filter((e) => e.status === "PLANNED").length;
  const p1 = SETUP_CATALOGUE.filter((e) => e.priority === "P1");
  const lines: string[] = [
    "# Setup catalogue",
    "",
    "<!-- Generated by `pnpm setup:catalogue` from src/server/modules/setup/catalogue.ts – do not edit by hand. -->",
    "",
    "Every configuration and control function of Setup (`/setup`), by category, with who may open it and how far it is",
    "built. The list follows the brief of prompt 19; it has **not** been checked against the live Zoho CRM account.",
    "",
    `**${SETUP_CATALOGUE.length} functions: ${done} done, ${partial} in progress, ${planned} planned.** Of the ${p1.length} go-live (P1) functions,`,
    `${p1.filter((e) => e.status === "DONE").length} are done, ${p1.filter((e) => e.status === "PARTIAL").length} are in progress and ${p1.filter((e) => e.status === "PLANNED").length} are planned.`,
    "",
    "- **Status** – *Done*: working. *In progress*: the core works, the note says what is missing. *Planned*: the page",
    "  exists and says \"Coming soon\".",
    "- **Tier** – **SA** Super Admin only · ADMIN Administrator (and Super Admin) · BA delegated Brand Admin, own brand",
    "  only · \"BA (planned)\": the brief allows Brand Admins, today the page is for administrators · All: every user.",
    "- **Pri** – P1 needed for go-live · P2 within three months · P3 later.",
    "",
  ];
  for (const c of SETUP_CATEGORY_DEFS) {
    lines.push(`## ${c.title}`, "", "| Function | What it does | Pri | Tier | Status | Page | Notes |", "|---|---|---|---|---|---|---|");
    for (const e of SETUP_CATALOGUE.filter((x) => x.category === c.key)) {
      const notes = [e.statusNote, e.reuse ? `Built by prompt ${e.reuse}` : null, e.external ? "Opened by its module permission, not by the Setup tier" : null, e.delegable ? "Can be delegated to other profiles (Setup permissions)" : null].filter(Boolean).join(". ");
      lines.push(`| ${cell(e.label)} | ${cell(e.description)} | ${e.priority} | ${tiers(e)} | ${STATUS[e.status]} | \`${hrefOf(e)}\` | ${cell(notes)} |`);
    }
    lines.push("");
  }
  lines.push(
    "## Cross-cutting features",
    "",
    "| Feature | Status | Notes |",
    "|---|---|---|",
    "| Setup home: category grid, search over names and descriptions, recently visited | Done | Recently visited is remembered in the browser |",
    "| Tier check on every page and service (`setupPermission`) | Done | `requireSetup(key)` on pages, `assertSetup(ctx, key)` in services; outside the tier → 404 |",
    "| Destructive operations: re-authentication + a second Super Admin (four eyes), audited | Done | Purge, mass delete, sample-data removal, authentication policies, revoking a Super Admin, disabling an administrator. Not yet: deleting a field that has data, restoring a backup (neither exists as a Setup function) |",
    "| Setup audit trail with before / after, who, when, address; diff view; one-click revert | In progress | Revert is offered for organisation settings that are not security policies |",
    "| Configuration as code: export, validate, import | In progress | Settings, roles, profiles, validation rules, custom fields, layouts, pipelines. Not workflow rules, approval processes, assignment rules or templates. No sandbox deploy with diff and rollback |",
    "| Impact preview | In progress | Sharing rules (records and users; cross-brand → refused) and validation rules (records that would be refused) |",
    "| Granular setup permissions per profile | In progress | Only the functions marked as delegable; never security or tier functions |",
    "| Safe defaults: Private and brand-owned | Done | The only default access is \"private by territory\"; there are no custom modules yet |",
    "",
  );
  return `${lines.join("\n")}`;
}

if (require.main === module) {
  const file = path.resolve(__dirname, "../docs/SETUP_CATALOGUE.md");
  fs.writeFileSync(file, renderCatalogue());
  console.log(`Wrote ${file}`);
}
